# Generated by Django 4.0.3 on 2022-03-17 23:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cage_number', models.IntegerField()),
                ('external_id', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Experiment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ExpirementGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('description', models.TextField()),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prototype.experiment')),
            ],
        ),
        migrations.CreateModel(
            name='Mouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ear_tag', models.CharField(choices=[('N', 'N'), ('R', 'R'), ('L', 'L'), ('RR', 'Rr'), ('LL', 'Ll'), ('B', 'B'), ('BB', 'Bb')], max_length=2)),
                ('experiment_id', models.IntegerField()),
                ('cage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prototype.cage')),
                ('experiment_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prototype.expirementgroup')),
            ],
        ),
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measurement_time', models.DateTimeField()),
                ('tumor_dimension_1', models.FloatField()),
                ('tumor_dimension_2', models.FloatField()),
                ('weight', models.FloatField()),
                ('mouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prototype.mouse')),
            ],
        ),
        migrations.AddField(
            model_name='cage',
            name='experiment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prototype.experiment'),
        ),
    ]
