# Generated by Django 4.0.3 on 2022-03-18 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prototype', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ExpirementGroup',
            new_name='ExperimentGroup',
        ),
    ]
