# Generated by Django 4.0.3 on 2022-04-04 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prototype', '0005_experiment_end_date_experiment_start_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExperimentTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('description', models.TextField()),
                ('scheduled_time', models.DateTimeField()),
                ('parent_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prototype.experimenttask')),
            ],
        ),
        migrations.CreateModel(
            name='TumorMeasurement',
            fields=[
                ('experimenttask_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='prototype.experimenttask')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prototype.measurement')),
            ],
            bases=('prototype.experimenttask',),
        ),
    ]
