# Generated by Django 4.0.3 on 2022-04-04 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prototype', '0006_experimenttask_tumormeasurement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experimenttask',
            name='parent_event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='prototype.experimenttask'),
        ),
        migrations.AlterField(
            model_name='experimenttask',
            name='scheduled_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='tumormeasurement',
            name='record',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='prototype.measurement'),
        ),
    ]
