# Generated by Django 4.0.3 on 2022-04-04 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prototype', '0009_experimenttask_experiment'),
    ]

    operations = [
        migrations.AddField(
            model_name='experimenttask',
            name='status',
            field=models.CharField(choices=[('ND', 'Notscheduled'), ('NS', 'Notstarted'), ('IP', 'Inprogress'), ('CP', 'Complete'), ('BK', 'Blocked')], default='NS', max_length=2),
            preserve_default=False,
        ),
    ]
