# Generated by Django 4.0.3 on 2022-04-04 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prototype', '0010_experimenttask_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurement',
            name='notes',
            field=models.TextField(default='na'),
            preserve_default=False,
        ),
    ]
